-- +goose Up
-- Create class-specific table for huntsman abilities
CREATE TABLE huntsman_abilities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    min_level INTEGER NOT NULL DEFAULT 1,
    UNIQUE(name)
);

-- Insert all huntsman abilities directly into the class-specific table
INSERT INTO huntsman_abilities (name, description, min_level) VALUES
-- Level 1 abilities
('Alertness', 'Reduces by one (−1) on a d6 roll the party''s chance to be surprized.', 1),
('Ambusher', 'When traversing the wilds alone or with others of like ability, the huntsman''s base surprize chance increases by one (+1) on a d6 roll. Furthermore, when outdoors, even an untrained party''s chance to surprize increases by one (+1) if the huntsman positions and prepares them accordingly.', 1),
('Climb', 'To ascend or descend sheer cliffs or walls without need of climbing gear, if lightly armoured or unarmoured, as a thief of equal level (see Table 16). Chance-in-twelve reduced by 4 if wearing medium armour; impossible in heavy armour. If vertical, the surface must be rough or cracked. At least one check must be made per 100 feet of climbing. Failure indicates the climber has slipped and fallen at about the midpoint of the check.', 1),
('Extraordinary', '+8% chance to perform extraordinary feats of strength and dexterity (see Chapter 3: Statistics, strength and dexterity).', 1),
('Harvest Venom', 'To extract venom sacs from snakes, spiders, giant insects, and the like, should the opportunity present and appropriate containers be available. Huntsmen learn to dissect venomous creatures. This skill is performed at a base 9-in-12 chance of success. If a 12 is rolled, a mishap occurs, and the huntsman is exposed (e.g., eyes, nose, skin) to the poisonous fluid. For more information on the extraction of venom, see Chapter 9: Combat, poison, venom harvesting.', 1),
('Hide', 'To conceal oneself in natural terrain, if the huntsman is lightly armoured or unarmoured. This ability is not possible in medium or heavy armour or in areas lacking natural cover (e.g., bare corridors, open plains with no vegetation).', 1),
('Move Silently', 'To stalk as a panther, moving with preternatural quiet, comparable to a thief of equal level (see Table 16), if the huntsman is lightly armoured or unarmoured. Chance-in-twelve reduced by 4 if wearing medium armour; impossible in heavy armour. This skill is executed at half the huntsman''s normal movement rate.', 1),
('Predator', 'Trained from earliest youth to hunt and kill animals both fleet and robust. The huntsman inflicts +1 hp damage per level of experience when combatting normal and giant-sized animals: amphibians, birds, crustaceans, dinosaurs, fishes, insects, mammals, and reptiles. Does not apply to constructs, dæmons, elementals, fungi, giants, humanoids, magical beasts, moulds, oozes, otherworldly and alien beings, slimes and jellies, or undead. When used in concert with a successful hide attempt, the initial attack roll is made at a +4 bonus.', 1),
('Subdue Animal', 'To soothe and tame an animal (normal, not magical) of hit dice equal to or less than the huntsman''s level. To succeed, the following steps must be completed: Through combat, physically reduce the animal to half or less its hit point total (the huntsman can assess this with accuracy). The huntsman must be a prominent aggressor in the beast''s impairment. Restrain the creature. Many a huntsman will use a bola, lasso, fighting net, or whip to make prone the target before attempting to restrain it. On the round following restraint, the huntsman attempts to assert mental and physical dominance. The base chance of success is 4-in-12. This chance-in-twelve may be increased by the following modifiers: +1 if the huntsman''s strength is 16+, +1 if the huntsman''s wisdom is 16+, +1 if the huntsman''s charisma is 16+, +1 if the huntsman''s level is 7+, +1 if the huntsman has dominated a member of this species before. Failure indicates the animal is impossible to tame. It may continue attempting to break free. Success indicates the animal is subdued; the huntsman must continue to restrain the creature for 1 turn (10 minutes), kneeling on it, commanding it, and forcing submission. Thereafter, it will be docile and relatively obedient. A defeated animal can be tamed to complete loyalty (ML 12) after 1d4 months of training. It can be trained to attack, fetch, guard, hunt, track, or perform other tasks. Multiple animals can be trained—even working in flawless synchronization if they are reasonably compatible—but their total hit dice can never exceed the huntsman''s level, and the training time for multiple animals is cumulative.', 1),
('Track', 'To stalk prey, tracing physical signs and scenting as a predator. A huntsman can track at the below suggested probabilities: Wilderness: A base 10-in-12 chance to find, identify, and follow fresh tracks outdoors or in natural caverns. Non-Wilderness: A base 3-in-12 chance to discern tracks in a dungeon, castle, city street, or like setting. Furthermore, the huntsman can identify in general terms the species tracked if it is a known animal type (e.g., a large feline, a heavy bovine, a small canine). N.B.: The referee may decrease or improve the chance-in-twelve to track based on prevailing circumstances.', 1),
('Weapon Mastery', 'Mastery of one weapon (+1 "to hit" and +1 damage). Additional weapons may be mastered at 4th, 8th, and 12th levels. As noted in Chapter 6: Equipment, the attack rate for melee weapons and the rates of fire for most missile weapons improve through weapon mastery. For more information on weapon mastery, see Chapter 9: Combat, weapon skill.', 1),
('Wilderness Survival', 'Hunting, trapping, fishing, boating, shelter building, fire building (including tribal smoke signals), logging, woodworking, raft building, and so on. These tasks are performed without need of a check; they are simply the huntsman''s province. Under adverse conditions, the referee may assign a reasonable probability of success. Whether a chance of failure applies is at the discretion of the referee, as reflected by the prevailing conditions and abilities of the huntsman.', 1),
('Wilderness Traps', 'To set an outdoor trap, including pits, deadfalls (falling logs/rocks), snares, and spring traps. The huntsman is also adept at finding and removing such traps. These tasks are performed as a thief of equal level performs the manipulate traps skill (see Table 16), but the huntsman has no facility with mechanical and/or magical traps.', 1),

-- Higher level abilities
('Werewolf Slayer', 'At 4th level, huntsmen develop the aptitude to slay lycanthropes. Indeed, when men and women suffer the curse of the beast, huntsmen rise to stamp them out. When wielding silver or magical weapons versus lycanthropes, huntsmen gain all the benefits of the predator ability, regardless of the advanced intelligence of the afflicted.', 4),
('Enlist Henchmen', 'At 6th level, a huntsman may seek or be sought out by one or more henchmen, classed individuals (typically of similar class, race, and/or culture) who become loyal followers. For more information, see Chapter 8: Adventure, hirelings and henchmen.', 6),
('Melee Expert', 'At 7th level, a huntsman''s standard melee attack rate improves from 1/1 to 3/2. Note that weapon mastery can further increase attack rate.', 7),
('Lordship', 'At 9th level, a huntsman who builds or assumes control of a wilderness fortress becomes a lord and is eligible to attract troops. More information is presented in Appendix B.', 9);

-- +goose Down
-- Clean up huntsman abilities table if reverting
DROP TABLE huntsman_abilities;