-- +goose Up
-- Create class-specific table for shaman abilities
CREATE TABLE shaman_abilities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    min_level INTEGER NOT NULL DEFAULT 1,
    UNIQUE(name)
);

-- Insert all shaman abilities directly into the class-specific table
INSERT INTO shaman_abilities (name, description, min_level) VALUES
-- Level 1 abilities
('Draw Poison', 'To draw and spit poison from a snakebite or another venomous wound, such as a scorpion sting or spider bite. The attempt must be made within 2 rounds of affliction for a 3-in-6 chance of success, within 4 rounds for a 2-in-6 chance of success, or within 6 rounds for a 1-in-6 chance of success. Success may revive one who has expired from poison, so long as a successful trauma survival check is made (see Chapter 3: Statistics, constitution). The deceased poison victim is restored to 0 hp, albeit at a price: permanent loss of 1 constitution point. For slower-acting venoms that do not prove immediately fatal, see also the medicine man ability. N.B.: Victims of envenomed blades or ingested poison are beyond the shaman''s aid.', 1),
('Harvest Venom', 'To extract venom sacs from snakes, spiders, giant insects, and the like, should the opportunity present and appropriate containers be available. Shamans learn to dissect venomous creatures in the field. This skill is performed at a base 9-in-12 chance of success. If a 12 is rolled, a mishap occurs, and the shaman is exposed (e.g., eyes, nose, skin) to the poisonous fluid. For more information on the extraction of venom, see Chapter 9: Combat, poison, venom harvesting.', 1),
('Magic Item Use', 'Can utilize magic items normally restricted to clerics and magicians.', 1),
('Medicine Man', 'To bind wounds, set sprains or broken bones, and concoct cures and antidotes for diseases and natural poisons, so long as the shaman has access to the herbs, roots, and ritualistic devices (e.g., drum, rattle) that are integral to shamanism. Gathering ingredients can be a time-consuming process, depending on circumstances. The process works as follows: Treat 1 person per day (including shaman) per level of experience; e.g., a 3rd-level shaman can treat up to three people per day. Process takes 1 turn to complete per person. Treatment involves the use of herbs, roots, and ritualistic dancing/percussion. Recipients immediately regain 1d4 hp and are stabilized if unconscious. Recipients can receive treatment only once per day. Treating Poison/Disease: When treating a natural (plant or animal) poison or disease, the shaman has an 8-in-12 chance to devise an antidote if familiar with the affliction; if unfamiliar, chance of success is reduced to 4-in-12. In either case, the chance-in-twelve is increased by one (+1) if the shaman has 16+ wisdom. The shaman may attempt to treat a poison or disease but once per week. The process takes 1 turn to complete and is predicated on the intervention of an ancestral spirit.', 1),
('Read Magic', 'The ability to decipher unintelligible magical inscriptions or symbols placed on weapons, armour, items, doors, walls, and other media by means of the sorcerer mark spell or other like methods.', 1),
('Scroll Use', 'To decipher and invoke ecclesiastical and thaumaturgical scrolls containing spells that correspond to the shaman''s chosen schools of sorcery, as included in the Cleric- or Druid Spell List (see Chapter 7: Sorcery, Table 99 or 100), and the Magician- or Necromancer Spell List (see Chapter 7: Sorcery, Table 93 or 96).', 1),
('Scroll Writing', 'To scribe a known spell onto a scroll, creating a single-use magical device at a cost of 500 gp + 100 gp per spell level. Materials include the finest vellum, papyrus, rare bark, or animal skin; a fresh quill; and sorcerer''s ink, such as sepia or the blood of a sacred animal. Alternatively, a shaman might sacrifice gems or jewellery of equal or greater value. Regardless, this involved process requires one week per spell level and must be completed on sacred ground.', 1),
('Sorcery', 'During character creation, the player must decide which two schools of magic their shaman casts. One choice is between cleric and druid spells; the other choice is between magician and necromancer spells. These spells are drawn from the Cleric- or Druid Spell List (see Chapter 7: Sorcery, Table 99 or 100), and the Magician- or Necromancer Spell List (see Chapter 7: Sorcery, Table 93 or 96). Spell school decisions are irreversible. The number and levels of spells cast per day are charted above (see Table 53), though shamans of high intelligence and high wisdom gain bonus spells cast per day (see Chapter 3: Statistics, intelligence and wisdom). For example, a 4th-level shaman with 13 intelligence and 13 wisdom can cast two level 1 spells and one level 2 cleric/druid spells per day, and two level 1 spells and one level 2 magician/necromancer spells per day. Shamans begin with knowledge of one level 1 cleric (or druid) spell. They also begin with a spell book, which may be in the form of thin stone tablets, bark sheets, animal skins, or shells laced together. At 2nd level, the shaman develops a level 1 magician (or necromancer) spell. Shamans develop one or more new spells at each level gain at the following schedule: 1st level: ×1 cleric/druid spell 2nd level: ×1 magician/necromancer spell 3rd level: ×1 cleric/druid spell 4th level: ×1 magician/necromancer spell 5th level: ×1 cleric/druid spell 6th level: ×1 magician/necromancer spell 7th to 12th levels: ×1 cleric/druid spell; ×1 magician/necromancer spell These spells are learnt automatically, with no need of qualification rolls, but they must be of castable levels (see Table 53 above). Developing new spells may include bonfire dancing, bone tossing, drumming or rattling, ice water immersion, or ritual sacrifice, during which the shaman may become temporarily possessed by a guiding spirit. Additional spells may be learnt outside of level training, but the process is more arduous (see Chapter 7: Sorcery, acquiring new spells).', 1),
('Totem', 'The sacred symbol of kinship that a clan, tribe, family shares with an animal, plant, or another natural object. Ofttimes the clan is named after the totem; e.g., Clan of the Wolf or the Frog Tribe. Totemic emblems are carved from stone, ivory, and other media. Once per week, the shaman may beseech the totem spirit for wisdom and guidance as per the contact otherworldly being spell, but requiring half the monetary sacrifice. A shaman might view a totem as a brother, guardian, or protector. Dualism is a distinct possibility; meaning it is possible that the totem is speaking and acting, not the shaman. A totem might be transferred from one person to another through elaborate ceremony, inheritance, or expropriation.', 1),

-- Level 3 abilities
('Turn Undead', 'At 3rd level, exert control over the undead and some dæmonic beings, causing them to flee and/or cower. At 3rd level the shaman has 1st-level turning ability (TA 1). Evil shamans can opt instead to compel the submission and service of these foul creatures. In either case, the cleric''s turn undead ability and Table 13 should be referenced for more information.', 3),

-- Level 4 abilities
('New Weapon Skill', 'At 4th, 8th, and 12th levels, become skilled in a new weapon that is not included in the favoured weapons list (noted above). This new proficiency is dependent upon training and practice (see Chapter 9: Combat, weapon skill).', 4),

-- Level 6 abilities
('Enlist Henchmen', 'At 6th level, a shaman may seek or be sought out by one or more henchmen, classed individuals (typically of similar class, race, and/or culture) who become loyal followers. In the case of a young shaman, it might be one whose totem has guided the adolescent to the shaman for learning. For more information, see Chapter 8: Adventure, hirelings and henchmen.', 6),

-- Level 9 abilities
('Lordship', 'At 9th level, a shaman who builds or assumes control of a wilderness fortress becomes a lord and is eligible to attract followers and troops. More information is presented in Appendix B.', 9),

-- Level 11 abilities
('Longevity', 'At 11th level, ageing process slows. For every 13 years (1 Hyperborean cycle), the shaman effectively ages but 1 year.', 11);

-- +goose Down
-- Clean up shaman abilities table if reverting
DROP TABLE shaman_abilities;