-- +goose Up
-- Create class-specific table for witch abilities
CREATE TABLE witch_abilities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    min_level INTEGER NOT NULL DEFAULT 1,
    UNIQUE(name)
);

-- Insert all witch abilities directly into the class-specific table
INSERT INTO witch_abilities (name, description, min_level) VALUES
-- Level 1 abilities
('Alchemy', 'To practice the sorcery-science of alchemy. Apprentice witches learn how to identify potions by taste alone; albeit the practice is not always safe. Apart from that, witches do not practice alchemy as magicians and other magician subclasses do; rather, they practice the brew decoction ability (see below).', 1),
('Brew Decoction', 'To brew an hallucinogen, nauseate, opaakkigen, paralytic, philtre, poison, or soporific potion in a cauldron suspended over a fire. All witches begin with an iron cauldron. Replacing it costs 50gp. A witch can brew decoction at the following schedule: 1st to 4th levels = ×1 decoction per month, 5th to 8th levels = ×3 decoctions per month, 9th to 12th levels = ×5 decoctions per month. It takes 48 hours to brew a decoction. Each is boiled down in the cauldron, retaining a potency that is measured by the witch''s casting ability (CA). To prepare a decoction, the necessary ingredients (animal blood, organs and parts; roots, fungi, herbs, mosses, etc.) can be collected in the witch''s native land at no material cost (though gathering them may require 1d6 days). Elsewhere, ingredients must be purchased at 100 gp per CA of potion. A brewed decoction must be imbibed by the victim. A successful death (poison) saving throw negates all effects, which otherwise will take place 1 turn later. Hallucinogens cause confusion (as the spell) for 1 turn per CA. Nauseates sicken for 1 hour per CA; natural 1 save results in death in 1d6 turns. Opaakkigens cause blindness for 3 turns per CA; natural 1 save results in permanence. Paralytics cause paralysis for 3 turns per CA. Philtres cause unremitting love for brewer (and brewer alone) for 1 year per CA unless dispel magic or remove curse is cast. Poisons cause harm or kill the victim (see below). Soporifics cause a sleep effect (as the spell) for 3 turns per CA. The potency of brewed poison depends upon the witch''s CA: CA 1 = brew ingestible I poison, CA 5 = brew ingestible II poison, CA 9 = brew ingestible III poison', 1),
('Familiar', 'To summon an ancestral, animistic, dæmonic, or elemental spirit which inhabits the body of a small animal (bat, cat, owl, rat, raven, snake, etc.) and functions as a familiar (singular creature with uncanny connexion to the sorcerer). The witch''s familiar has 1d3+3 hp and is of uncanny intellect. To summon a familiar, the witch must engage in a 24-hour ritual. To determine the result, roll 2d8 on Table 10, located at the magician entry. Like the magician''s familiar, the witch''s familiar always attends and abides the will of its master, and it has a perfect morale score (ML 12); otherwise, the benefits differ. For the witch, they are as follows: The witch and familiar share a spiritual and empathic bond of unlimited range. At any range, the witch can see and hear through the animal; sight is narrowly focused, sounds reverberate metallically. The following spells, if known, can be cast through the familiar: detect evil, detect illusion, detect magic, detect malady, detect undead, locate the dead; detect invisibility, detect silence, find traps, locate object, perceive heartbeat. If the familiar is killed, the witch must make a death saving throw. A failed saving throw results in 3d6 hp damage sustained; if the saving throw is failed by a margin of 5 or more, the witch must make a trauma survival check (see Chapter 3: Statistics, constitution) or die. Even if the witch survives, loss of a familiar is physically and emotionally draining; it takes 3d4 months before the witch can seek a new one.', 1),
('Read Magic', 'The ability to decipher unintelligible magical inscriptions or symbols placed on weapons, armour, items, doors, walls, and other media by means of the sorcerer mark spell or other like methods.', 1),
('Scroll Use', 'To decipher and invoke scrolls with spells that are included in the Witch Spell List (see Chapter 7: Sorcery, Table 98), unless the scroll was created by an ecclesiastical sorcerer (one who casts cleric or druid spells).', 1),
('Scroll Writing', 'To scribe a known spell onto a scroll, creating a single-use magical device at a cost of 500 gp + 100 gp per spell level. Materials may include the finest vellum, paper, or papyrus; a fresh quill; and sorcerer''s ink, such as sepia. This involved process requires one week per spell level.', 1),
('Sorcery', 'Witches cast spells that they memorize from arcane tomes; they also gain divine favour from animistic spirits, dæmons, netherworldly beings, and celestial powers. The number and levels of spells cast per day are charted above (see Table 40), though witches of high intelligence gain bonus spells cast per day (see Chapter 3: Statistics, intelligence). For example, a 4th-level witch with 13 intelligence can cast four level 1 spells and two level 2 spells per day. The witch begins with a spell book that contains three level 1 spells drawn from the Witch Spell List (see Chapter 7: Sorcery, Table 98). Through personal research and unspeakable pacts, witches develop one new spell at each level gain; this spell is learnt automatically, with no need of a qualification roll, but it must be of a castable level (see Table 40 above). Initial no. of spells known: ×3 No. of spells gained per level: ×1 Additional spells may be learnt outside of level training, but the process is more arduous (see Chapter 7: Sorcery, acquiring new spells).', 1),

-- Level 4 abilities
('New Weapon Skill', 'At 4th, 8th, and 12th levels, become skilled in a new weapon that is not included in the favoured weapons list (noted above). This new proficiency is dependent upon training and practice (see Chapter 9: Combat, weapon skill).', 4),

-- Level 5 abilities
('Dance of Beguilement', 'At 5th level, the ability to perform an entrancing dance, moving in a rhythmic manner to entice a number of human and/or humanoid observers equal to the witch''s level of experience. The dance requires 1 turn to perform, and victims are usually unaware of the underlying enchantment. A sorcery saving throw (made at a −1 penalty if fire is employed) negates the effects. The save also is modified by willpower adjustment (see Chapter 3: Statistics, wisdom), if applicable. Victims become entranced by the witch, first staring dumbfounded and then enthusiastically desiring to please the witch. Beguilement lasts as long as the witch remains visible. In one victim, the witch can plant a suggestion (as the spell), which the victim is compelled to obey; however, if the suggestion is unreasonable, the victim is allowed a second saving throw to shake off the cobwebs of his or her mind.', 5),
('Effigy', 'At 5th level, create an effigy of an enemy human or humanoid. It is fashioned from clay, cloth, or wicker, averages 4–12 inches tall, and requires no more than a crude resemblance to the intended victim. It takes one week to complete the creation. Then, the effigy is enchanted by means of a 6-turn (1-hour) ritual that requires the handling of a personal item (or hair) taken from the intended victim. To activate the effigy, the witch must be within eyesight of the intended victim. A final incantation is spoken, and if the victim fails a sorcery saving throw (modified by willpower adjustment, if applicable), the witch can affect the victim through the effigy as follows: Control victim''s bodily movements, within reason, like a puppeteer. Stab the effigy once, wounding the victim for 3d8 hp damage. Pinprick the effigy, causing 1d2 hp damage for as many times as the witch has levels of experience. This effect can be spread out over days. At 12th-level, strangle the effigy; victim must make a death saving throw or die. If an effigy victim touches his or her own effigy, the effect is terminated, the spell broken. N.B.: A witch also can use this ability in conjunction with a clairvoyance spell or the like, manipulating or harming the victim from afar.', 5),

-- Level 6 abilities
('Enlist Henchmen', 'At 6th level, a witch may seek or be sought out by one or more henchmen, classed individuals (typically of similar class, race, and/or culture) who become loyal followers. For more information, see Chapter 8: Adventure, hirelings and henchmen.', 6),

-- Level 7 abilities
('Animate Broom', 'At 7th level, transform a normal broom into a magic broom, following an exhausting 24-hour ritual that involves binding a dæmonic, ghostly, or animistic spirit. The broom is an intelligent item that can be commanded by the witch. If anyone but the witch attempts to ride it, the broom unceremoniously dumps the violator, unless the witch commands otherwise. The broom has 80 MV if it bears one person of 250 pounds or less; it can carry two persons whose total weight does not exceed 500 pounds at 60 MV. A witch can maintain but one magic broom. If it is destroyed, the witch suffers 3d6 hp damage. The broom is considered a creature of AC 3, HD 7 (hp 20), and is susceptible to fire (+1 hp per die of damage). It functions thrice per day, for a maximum period of 6 turns (1 hour) per use. It requires 1 turn to recharge between uses.', 7),

-- Level 9 abilities
('Lordship', 'At 9th level, a witch who builds or assumes control of a stronghold becomes a lord and is eligible to attract troops. More information is presented in Appendix B.', 9);

-- +goose Down
-- Clean up witch abilities table if reverting
DROP TABLE witch_abilities;