-- +goose Up
-- SQL in this section is executed when the migration is applied

INSERT INTO equipment (name, description, cost, weight) VALUES
--('Arrow Quiver', 'Leather arrow quiver with dozen capacity', 1.0, 1),
--('Backpack', 'Leather backpack with 50-lb. capacity', 5.0, 2),
('Bandages, Gauze', '10-ft. ball of gauze bandages', 0.1, 0),
('Belladonna', 'Dried bunch of belladonna. 1:4 chance cures lycanthropy; 1:10 chance fatal pending death (poison) save', 30.0, 0),
('Blanket, Winter', 'Warm winter blanket for cold weather', 0.5, 3),
('Block and Tackle', 'Mechanical device used for lifting heavy objects', 5.0, 5),
--('Bolt Case', 'Leather bolt case with score capacity', 1.0, 1),
('Book, Blank', 'Leather cover with sewn binding, containing 50 parchment pages', 50.0, 1),
('Bottle', 'Glass or ceramic bottle with 12-oz. capacity', 1.0, 0),
('Bow Case', 'Waterproof leather bow case', 10.0, 1),
('Candle, Beeswax', '8-hour burn time, provides 5-ft. radius of light', 0.1, 0),
('Candle, Tallow', '2-hour burn time, provides 5-ft. radius of light', 0.01, 0),
('Case, Map or Scroll (brass)', 'Brass case for maps or scrolls', 5.0, 0),
('Case, Map or Scroll (leather)', 'Leather case for maps or scrolls', 2.0, 0),
('Chain, Iron, Heavy', 'Heavy iron chain, ó-inch thick, cost per foot', 5.0, 3),
('Chain, Iron, Light', 'Light iron chain, .-inch thick, cost per foot', 3.0, 1),
('Chalk', 'Piece of chalk for writing', 0.01, 0),
('Chisel', 'Metal-, stone-, or wood-cutting chisel', 0.5, 1),
('Cord, Sinew', '100-ft. ball of sinew cord', 0.02, 0),
('Crampons', 'Pair of crampons, includes ice axe (WC 1, 1d3 hp damage)', 2.0, 1),
('Dice, Ivory', 'Pair of ivory dice for games of chance', 0.2, 0),
('Fishing Hooks', 'Set of 12 fishing hooks', 0.5, 0),
('Fishing Net', '10 × 10 ft. fishing net', 3.0, 3),
('Fishing String', '100-ft. ball of fishing string', 0.01, 0),
('Glue', '1-qt. clay pot of powdered glue, must add hot water', 0.03, 2),
('Grappling Hook', 'Iron grappling hook for climbing', 15.0, 3),
('Grease', '1-qt. clay pot of grease', 0.02, 2),
('Hammer, Small', 'Small iron hammer (WC 1, 1d2 hp damage)', 0.5, 2),
('Helmet', 'Standard helmet, normally included with armour purchase', 10.0, 2),
('Horn, Drinking', 'Horn used for drinking', 0.1, 1),
('Horn, Hunting', 'Horn used for hunting signals', 2.0, 1),
('Hourglass', 'Brass hourglass for time keeping', 25.0, 1),
('Ink and Quill', 'Writing implements for documents and scrolls', 10.0, 0),
('Lantern, Bull''s-Eye', 'Lantern providing 15-ft. radius of light and 60-ft. narrow beam', 10.0, 2),
('Lantern, Hooded', 'Lantern providing 30-ft. radius of light', 7.0, 2),
('Marbles', 'Set of about 20 glass or ceramic marbles in a soft leather pouch', 0.2, 0),
('Mirror, Steel', 'Polished steel mirror, 3 × 5 inches', 5.0, 1),
('Mirror, Silver', 'Silver mirror, 3 × 5 inches', 20.0, 1),
('Nails', 'Set of 20 iron nails, 4-inch length', 0.1, 0),
('Needle, Blowgun', 'Needle for use with a blowgun', 0.1, 0),
('Needle, Sewing', 'Common sewing needle', 0.01, 0),
('Oil, Incendiary', '8-oz. flask of Greek fire', 35.0, 1),
('Oil, Lamp', '8-oz. flask of lamp oil, 6-hour burn time', 0.1, 1),
('Padlock and Key', 'Padlock with matching key', 10.0, 1),
('Parchment', 'Single sheet of parchment for writing', 1.0, 0),
('Pole', '10-ft. wooden pole for various uses', 0.3, 5),
('Pouch, Hard Leather', 'Hard leather pouch that holds 6 potions or 3 scrolls, includes belt loops', 5.0, 0),
('Pouch, Soft Leather', 'Soft leather pouch that holds 6–9 cubic inches of material, includes drawstring', 0.07, 0),
('Pry Bar', '16-inch iron pry bar', 1.0, 3),
('Ring, Signet', 'Pewter signet ring for sealing documents', 5.0, 0),
('Rope, Hemp', '50-ft. length of ó-inch hemp rope', 1.0, 5),
('Rope, Silk', '50-ft. length of .-inch silk rope', 15.0, 2),
('Rope Ladder, Hemp', '50-ft. hemp rope ladder with wooden crosspieces', 5.0, 12),
('Rope Ladder, Silk', '50-ft. silk rope ladder with wooden crosspieces', 50.0, 6),
('Sack, Large', 'Large cloth or leather sack with 40-lb. capacity', 0.3, 0),
('Sack, Small', 'Small cloth or leather sack with 20-lb. capacity', 0.1, 0),
('Scabbard, Leather', 'Leather scabbard with baldric, normally included with sword purchase', 0.5, 0),
('Scabbard, Metal', 'Metal scabbard with baldric', 0.8, 1),
('Sheath, Dagger', 'Leather dagger sheath, normally included with dagger purchase', 0.3, 0),
('Skis', 'Pair of skis with poles for traveling over snow', 10.0, 8),
('Soap', 'Bar of soap for cleaning', 0.5, 1),
('Spikes, Iron', 'Set of 4 iron spikes, 9-inch length', 0.1, 1),
('Spyglass', 'Spyglass with ×3 magnification', 750.0, 1),
('Stakes and Wooden Mallet', 'Set of 4 stakes with a wooden mallet', 1.0, 2),
('Tent, 1-Person', 'Canvas tent for one person', 5.0, 5),
('Tent, 2-Person', 'Canvas tent for two people', 7.0, 7),
('Tent, 4-Person', 'Canvas tent for four people', 12.0, 10),
('Thieves'' Tools', 'Set containing file, oil dropper, picks, pincers, skeleton keys, small hammer, small saw, small wedge, and wire', 25.0, 3),
('Tinderbox', 'Contains flint and steel, paraffin, and wood powder for starting fires', 2.0, 1),
('Torch', 'Torch with oil- and resin-soaked rope wrap, 1- to 2-hour burn time, provides 30-ft. radius of light, can be used as a single-use weapon dealing 1d4 hp damage', 0.02, 1),
('Water-/Wineskin', 'Container with ó-gallon capacity for water or wine', 1.0, 0),
('Wax, Bees-', 'Block of beeswax', 0.03, 1),
('Wire', '100-ft. spool of wire with 50-lb. test strength', 3.0, 0),
('Wolfsbane', 'Dried bunch of wolfsbane, 2:6 chance to drive off lycanthropes if affixed to spear tip', 25.0, 0),
('Writing Stick', 'Charcoal writing stick', 0.1, 0);

-- +goose Down
-- SQL in this section is executed when the migration is rolled back

DELETE FROM equipment;