// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Ammo struct {
	ID        int64
	Name      string
	Cost      float64
	Weight    int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Armor struct {
	ID              int64
	Name            string
	ArmorType       string
	Ac              int64
	Cost            float64
	DamageReduction int64
	Weight          int64
	WeightClass     string
	MovementRate    int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Character struct {
	ID               int64
	UserID           int64
	Name             string
	Class            string
	Level            int64
	ExperiencePoints int64
	Strength         int64
	Dexterity        int64
	Constitution     int64
	Wisdom           int64
	Intelligence     int64
	Charisma         int64
	HitPoints        int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Container struct {
	ID           int64
	Name         string
	MaxWeight    int64
	AllowedItems string
	Cost         float64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Equipment struct {
	ID          int64
	Name        string
	Description string
	Cost        float64
	Weight      int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type FighterClassDatum struct {
	Level            int64
	ExperiencePoints int64
	HitDice          string
	SavingThrow      int64
	FightingAbility  int64
}

type Inventory struct {
	ID            int64
	CharacterID   int64
	MaxWeight     float64
	CurrentWeight float64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type InventoryItem struct {
	ID          int64
	InventoryID int64
	ItemType    string
	ItemID      int64
	Quantity    int64
	IsEquipped  bool
	Notes       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MagicItem struct {
	ID          int64
	Name        string
	ItemType    string
	Description string
	Charges     sql.NullInt64
	Cost        float64
	Weight      int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Potion struct {
	ID          int64
	Name        string
	Description string
	Uses        int64
	Weight      int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Ring struct {
	ID          int64
	Name        string
	Description string
	Cost        float64
	Weight      int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Shield struct {
	ID              int64
	Name            string
	Cost            float64
	Weight          int64
	DefenseModifier int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Spell struct {
	ID           int64
	CharacterID  int64
	Name         string
	MagLevel     int64
	CryLevel     int64
	IllLevel     int64
	NecLevel     int64
	PyrLevel     int64
	WchLevel     int64
	ClrLevel     int64
	DrdLevel     int64
	Range        string
	Duration     string
	AreaOfEffect sql.NullString
	Components   sql.NullString
	Description  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type SpellScroll struct {
	ID           int64
	SpellID      int64
	CastingLevel int64
	Cost         float64
	Weight       int64
	Description  sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Treasure struct {
	ID             int64
	CharacterID    sql.NullInt64
	PlatinumCoins  int64
	GoldCoins      int64
	ElectrumCoins  int64
	SilverCoins    int64
	CopperCoins    int64
	Gems           sql.NullString
	ArtObjects     sql.NullString
	OtherValuables sql.NullString
	TotalValueGold float64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Weapon struct {
	ID              int64
	Name            string
	Category        string
	WeaponClass     int64
	Cost            float64
	Weight          int64
	RangeShort      sql.NullInt64
	RangeMedium     sql.NullInt64
	RangeLong       sql.NullInt64
	RateOfFire      sql.NullString
	Damage          string
	DamageTwoHanded sql.NullString
	Properties      sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
