// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Ability struct {
	ID          int64
	Name        string
	Description string
}

type Ammo struct {
	ID        int64
	Name      string
	Cost      float64
	Weight    int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Armor struct {
	ID              int64
	Name            string
	ArmorType       string
	Ac              int64
	Cost            float64
	DamageReduction int64
	Weight          int64
	WeightClass     string
	MovementRate    int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type BardDruidSpell struct {
	Level            int64
	SpellSlotsLevel1 int64
	SpellSlotsLevel2 int64
	SpellSlotsLevel3 int64
	SpellSlotsLevel4 int64
}

type BardIllusionistSpell struct {
	Level            int64
	SpellSlotsLevel1 int64
	SpellSlotsLevel2 int64
	SpellSlotsLevel3 int64
	SpellSlotsLevel4 int64
}

type BerserkerNaturalAc struct {
	ID        int64
	ClassName string
	Level     int64
	NaturalAc int64
}

type Character struct {
	ID                 int64
	UserID             int64
	Name               string
	Class              string
	Level              int64
	ExperiencePoints   int64
	Strength           int64
	Dexterity          int64
	Constitution       int64
	Wisdom             int64
	Intelligence       int64
	Charisma           int64
	MaxHitPoints       int64
	CurrentHitPoints   int64
	TemporaryHitPoints int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type ClassAbilityMapping struct {
	ClassName string
	AbilityID int64
	MinLevel  int64
}

type ClassDatum struct {
	ID               int64
	ClassName        string
	Level            int64
	ExperiencePoints int64
	HitDice          string
	SavingThrow      int64
	FightingAbility  int64
	CastingAbility   sql.NullInt64
	SpellSlotsLevel1 sql.NullInt64
	SpellSlotsLevel2 sql.NullInt64
	SpellSlotsLevel3 sql.NullInt64
	SpellSlotsLevel4 sql.NullInt64
	SpellSlotsLevel5 sql.NullInt64
	SpellSlotsLevel6 sql.NullInt64
}

type ClassThiefSkillMapping struct {
	ID        int64
	ClassName string
	SkillID   int64
}

type ClericTurningAbility struct {
	ID             int64
	ClassName      string
	Level          int64
	TurningAbility int64
}

type Container struct {
	ID           int64
	Name         string
	MaxWeight    int64
	AllowedItems string
	Cost         float64
	Weight       int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Equipment struct {
	ID          int64
	Name        string
	Description string
	Cost        float64
	Weight      int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Inventory struct {
	ID                  int64
	CharacterID         int64
	MaxWeight           float64
	CurrentWeight       float64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	BaseEncumbered      float64
	BaseHeavyEncumbered float64
	MaximumCapacity     float64
	IsEncumbered        bool
	IsHeavyEncumbered   bool
	IsOverloaded        bool
}

type InventoryItem struct {
	ID          int64
	InventoryID int64
	ItemType    string
	ItemID      int64
	Quantity    int64
	IsEquipped  bool
	Notes       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type KnownSpell struct {
	ID          int64
	CharacterID int64
	SpellID     int64
	SpellName   string
	SpellLevel  int64
	SpellClass  string
	IsMemorized bool
	Notes       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MagicItem struct {
	ID          int64
	Name        string
	ItemType    string
	Description string
	Charges     sql.NullInt64
	Cost        float64
	Weight      int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MonkAcBonu struct {
	Level   int64
	AcBonus int64
}

type MonkEmptyHandDamage struct {
	Level  int64
	Damage string
}

type NecromancerTurningAbility struct {
	ClassName      string
	Level          int64
	TurningAbility int64
}

type PaladinTurningAbility struct {
	ID             int64
	ClassName      string
	Level          int64
	TurningAbility int64
}

type Potion struct {
	ID          int64
	Name        string
	Description string
	Uses        int64
	Weight      int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PreparedSpell struct {
	ID          int64
	CharacterID int64
	SpellID     int64
	SpellName   string
	SpellLevel  int64
	SpellClass  string
	SlotIndex   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PriestTurningAbility struct {
	Level          int64
	TurningAbility int64
}

type PurloinerTurningAbility struct {
	Level          int64
	TurningAbility int64
}

type RangerDruidSpellSlot struct {
	ClassLevel int64
	SpellLevel int64
	Slots      int64
}

type RangerMagicianSpellSlot struct {
	ClassLevel int64
	SpellLevel int64
	Slots      int64
}

type Ring struct {
	ID          int64
	Name        string
	Description string
	Cost        float64
	Weight      int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RunesPerDay struct {
	ID        int64
	ClassName string
	Level     int64
	Level1    sql.NullInt64
	Level2    sql.NullInt64
	Level3    sql.NullInt64
	Level4    sql.NullInt64
	Level5    sql.NullInt64
	Level6    sql.NullInt64
}

type ShamanArcaneSpell struct {
	Level            int64
	SpellSlotsLevel1 int64
	SpellSlotsLevel2 int64
	SpellSlotsLevel3 int64
	SpellSlotsLevel4 int64
	SpellSlotsLevel5 int64
	SpellSlotsLevel6 int64
}

type ShamanDivineSpell struct {
	Level            int64
	SpellSlotsLevel1 int64
	SpellSlotsLevel2 int64
	SpellSlotsLevel3 int64
	SpellSlotsLevel4 int64
	SpellSlotsLevel5 int64
	SpellSlotsLevel6 int64
}

type ShamanTurningAbility struct {
	Level          int64
	TurningAbility int64
}

type Shield struct {
	ID              int64
	Name            string
	Cost            float64
	Weight          int64
	DefenseModifier int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Spell struct {
	ID           int64
	Name         string
	MagLevel     int64
	CryLevel     int64
	IllLevel     int64
	NecLevel     int64
	PyrLevel     int64
	WchLevel     int64
	ClrLevel     int64
	DrdLevel     int64
	Range        string
	Duration     string
	AreaOfEffect sql.NullString
	Components   sql.NullString
	Description  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type SpellScroll struct {
	ID           int64
	SpellID      int64
	CastingLevel int64
	Cost         float64
	Weight       int64
	Description  sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Spellbook struct {
	ID          int64
	Name        string
	Description sql.NullString
	TotalPages  int64
	UsedPages   int64
	Value       int64
	Weight      float64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SpellbookSpell struct {
	ID             int64
	SpellbookID    int64
	SpellID        int64
	CharacterClass string
	PagesUsed      int64
}

type ThiefSkill struct {
	ID        int64
	SkillName string
	Attribute string
}

type ThiefSkillProgression struct {
	ID            int64
	SkillID       int64
	LevelRange    string
	SuccessChance string
}

type Treasure struct {
	ID             int64
	CharacterID    sql.NullInt64
	PlatinumCoins  int64
	GoldCoins      int64
	ElectrumCoins  int64
	SilverCoins    int64
	CopperCoins    int64
	Gems           sql.NullString
	ArtObjects     sql.NullString
	OtherValuables sql.NullString
	TotalValueGold float64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Weapon struct {
	ID              int64
	Name            string
	Category        string
	WeaponClass     int64
	Cost            float64
	Weight          int64
	RangeShort      sql.NullInt64
	RangeMedium     sql.NullInt64
	RangeLong       sql.NullInt64
	RateOfFire      sql.NullString
	Damage          string
	DamageTwoHanded sql.NullString
	Properties      sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
