// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateArmor(ctx context.Context, arg CreateArmorParams) (sql.Result, error)
	CreateCharacter(ctx context.Context, arg CreateCharacterParams) (sql.Result, error)
	CreateEquipment(ctx context.Context, arg CreateEquipmentParams) (sql.Result, error)
	CreateMagicItem(ctx context.Context, arg CreateMagicItemParams) (sql.Result, error)
	CreatePotion(ctx context.Context, arg CreatePotionParams) (sql.Result, error)
	CreateShield(ctx context.Context, arg CreateShieldParams) (sql.Result, error)
	CreateSpell(ctx context.Context, arg CreateSpellParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	CreateWeapon(ctx context.Context, arg CreateWeaponParams) (sql.Result, error)
	DeleteArmor(ctx context.Context, id int64) (sql.Result, error)
	DeleteCharacter(ctx context.Context, id int64) (sql.Result, error)
	DeleteEquipment(ctx context.Context, id int64) (sql.Result, error)
	DeleteMagicItem(ctx context.Context, id int64) (sql.Result, error)
	DeletePotion(ctx context.Context, id int64) (sql.Result, error)
	DeleteShield(ctx context.Context, id int64) (sql.Result, error)
	DeleteSpell(ctx context.Context, id int64) (sql.Result, error)
	DeleteUser(ctx context.Context, id int64) (sql.Result, error)
	DeleteWeapon(ctx context.Context, id int64) (sql.Result, error)
	GetArmor(ctx context.Context, id int64) (Armor, error)
	GetArmorByName(ctx context.Context, name string) (Armor, error)
	GetCharacter(ctx context.Context, id int64) (Character, error)
	GetCharactersByUser(ctx context.Context, userID int64) ([]Character, error)
	GetEquipment(ctx context.Context, id int64) (Equipment, error)
	GetEquipmentByName(ctx context.Context, name string) (Equipment, error)
	GetMagicItem(ctx context.Context, id int64) (MagicItem, error)
	GetMagicItemByName(ctx context.Context, name string) (MagicItem, error)
	GetPotion(ctx context.Context, id int64) (Potion, error)
	GetPotionByName(ctx context.Context, name string) (Potion, error)
	GetShield(ctx context.Context, id int64) (Shield, error)
	GetShieldByName(ctx context.Context, name string) (Shield, error)
	GetSpell(ctx context.Context, id int64) (Spell, error)
	GetSpellsByCharacter(ctx context.Context, characterID int64) ([]Spell, error)
	GetUser(ctx context.Context, id int64) (GetUserRow, error)
	GetWeapon(ctx context.Context, id int64) (Weapon, error)
	GetWeaponByName(ctx context.Context, name string) (Weapon, error)
	ListArmors(ctx context.Context) ([]Armor, error)
	ListCharacters(ctx context.Context) ([]Character, error)
	ListEquipment(ctx context.Context) ([]Equipment, error)
	ListMagicItems(ctx context.Context) ([]MagicItem, error)
	ListMagicItemsByType(ctx context.Context, itemType string) ([]MagicItem, error)
	ListPotions(ctx context.Context) ([]Potion, error)
	ListShields(ctx context.Context) ([]Shield, error)
	ListSpells(ctx context.Context) ([]Spell, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	ListWeapons(ctx context.Context) ([]Weapon, error)
	UpdateArmor(ctx context.Context, arg UpdateArmorParams) (sql.Result, error)
	UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (sql.Result, error)
	UpdateEquipment(ctx context.Context, arg UpdateEquipmentParams) (sql.Result, error)
	UpdateMagicItem(ctx context.Context, arg UpdateMagicItemParams) (sql.Result, error)
	UpdatePotion(ctx context.Context, arg UpdatePotionParams) (sql.Result, error)
	UpdateShield(ctx context.Context, arg UpdateShieldParams) (sql.Result, error)
	UpdateSpell(ctx context.Context, arg UpdateSpellParams) (sql.Result, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error)
	UpdateWeapon(ctx context.Context, arg UpdateWeaponParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
