// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: thief_skills.sql

package db

import (
	"context"
)

const getThiefSkillsByLevel = `-- name: GetThiefSkillsByLevel :many
SELECT 
    id,
    skill_name,
    attribute,
    level,
    success_chance
FROM thief_skills
WHERE level = ?
ORDER BY skill_name
`

func (q *Queries) GetThiefSkillsByLevel(ctx context.Context, level int64) ([]ThiefSkill, error) {
	rows, err := q.query(ctx, q.getThiefSkillsByLevelStmt, getThiefSkillsByLevel, level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThiefSkill{}
	for rows.Next() {
		var i ThiefSkill
		if err := rows.Scan(
			&i.ID,
			&i.SkillName,
			&i.Attribute,
			&i.Level,
			&i.SuccessChance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
